### ISSUE TITLE
publication et licence des données

### ISSUE THREAD

**Issue by vinber** [anct-carto/france_services#1]
Bonjour,
Pourriez vous publier les données sur data.gouv ?

Peut être aussi imaginer un stockage autre que google ?

Cela rejoint cette question de la précédente carte (https://github.com/anct-carto/France-services/issues/1).

**Comment by hassenchg** [comment]
Bonjour,

Le jeu de données est en cours de fiabilisation et devrait être déposé, sous licence ouverte 2.0, sur la page data-gouv de l'ANCT vers la fin du mois de février. 

A l'issue de la création de cette page, le fichier README sera actualisé pour y inclure le lien renvoyant vers les données. 

Avec nos excuses pour le délais de réponse,

Cordialement,
Le service cartographie de l'ANCT

**Comment by vinber** [comment]
Bonsoir,
Je découvre qu'une version est déjà présente, extraite d'un google drive ....

https://www.data.gouv.fr/fr/datasets/liste-des-maisons-france-services/

**Comment by hassenchg** [comment]
> Bonsoir, Je découvre qu'une version est déjà présente, extraite d'un google drive ....
> 
> https://www.data.gouv.fr/fr/datasets/liste-des-maisons-france-services/

Bonjour,

La fiabilisation du jeu de données a malheureusement pris du retard par rapport au calendrier initial. 

Je vous informe que la liste et localisation des France services est désormais mise à disposition sur la page data-gouv : 
https://www.data.gouv.fr/fr/datasets/liste-des-structures-france-services/ 
La description des variables et les conditions d'utilisations/réutilisations sont détaillées dans le fichier de métadonnées adjoint au jeu de données.
Pour le reste, le fichier est bien sous licence ouverte 2.0

Le fichier README de la carte interactive sera prochainement actualisé pour prendre en compte cette nouvelle information.

Concernant la version extraite du google drive que vous avez partagé, je ne recommande pas son usage en raison d'une qualité moyenne sur la partie géographique - raison pour laquelle il n'y a pas eu de publication de données. 
Par ailleurs, la solution du google drive sera très bientôt abandonnée, au profit d'une alimentation différente à définir - par data-gouv directement ou par un .json à la racine du projet. 

Avec mes excuses (encore une fois) pour le retard de la réponse.

Cordialement,

Hassen Chougar
Service cartographie de l'ANCT

**Comment by vinber** [comment]
Bonjour,

> Avec mes excuses (encore une fois) pour le retard de la réponse.

il faut mieux une réponse en retard que pas de réponse. Je suppose que répondre aux issues githb n'est pas votre seule activité :)

merci pour le lien

Bonne journée
